### PR TITLE
[api-extractor] Fix roll up of default exports

### LINKED ISSUE #1007: [api-extractor] Roll up of default export is not valid TypeScript
### Minimal example

Use the following snippet as entry file.

```ts
// index.ts
const example = 'foo'

export default example
```

This outputs:

```ts
// index.d.ts
export declare const default = "foo";
```

There, the TypeScript compiler errors with "Variable declaration expected" because the variable has the name `default`. To solve the issue the file must be manually edited as to match the following:

```ts
declare const example = "foo";

export default example;
```

### PR DESCRIPTION
**Pull request by yacinehmito**
This fixes #1007.

I managed to fix the bug after a lot of trial and error. The code might not be good enough.

Also, I added a new integration test package (`api-extractor-test-06`); this might have been overkill. It's a lot of code for too little a reward but, as there can only be a single root default export per entry, I had to resort to it.

Let me know if I need to change anything.

### CODE REVIEW

**Comment by yacinehmito** [comment]
> Instead of adding a new flag to identify the default export, should the condition astSymbol.nameForEmit === "default" already contain such information?

There's no `nameForEmit` on the AST Symbol.
From the entity we can try to guess whether it was exported as a default export only if it has been defined while it was being exported. Example:

```
export default class DefaultClass {};
```

In this situation we can do `entity.astSymbol.followedSymbol.name === 'default'` because the exported member belongs in the same AST branch as the export.

However in this situation we cannot have the data back:

```
const defaultFunctionStatement = () => {};

export default defaultFunctionStatement;
```

This entity represents `const defaultFunctionStatement = () => {};` so we cannot trace it back to `export default defaultFunctionStatement;` directly.

I'm willing to remove the flag if I'm provided a hint to solving that problem.

**Comment by adventure-yunfei** [comment]
> There's no `nameForEmit` on the AST Symbol.

Sorry I didn't describe it clearly. I meant for `collectorEntity.nameForEmit`.

> ```ts
> const defaultFunctionStatement = () => {};
> 
> export default defaultFunctionStatement;
> ```
> 
> This entity represents `const defaultFunctionStatement = () => {};` so we cannot trace it back to `export default defaultFunctionStatement;` directly.

As far as I know, CollectorEntity `nameForEmit` is to trace the export name (and ensured that there're no name conflicts with other un-exported items), not the original declaration. So in this case, this check still works. (and I've tested it.)

**Comment by yacinehmito** [comment]
> So in this case, this check still works. 

It doesn't with my changes because the whole point is to not change `nameForEmit` so that it's not `default` anymore for exported defaults. Which means that now this information must be carried somewhere else.

More specifically, when an entity is exported it is given the name of the exported identifier. Otherwise it is given the name of the AST Symbol. Because we want to use the latter in the case of a default export, I introduces a special rule as seen here: https://github.com/Microsoft/web-build-tools/pull/1008/files#diff-654d6159f379a5a12feb80338aeef279R255
Because `nameForEmit` is computed from `originalName`, we loose the information.

What I can do though is leave `originalName` alone and only affect `nameForEmit`. This way I can use `originalName` to identify whether it was a default export. I'll try this a report back.

**Comment by yacinehmito** [comment]
@adventure-yunfei It worked like a charm! I managed to get rid of `exportedAsDefault`. Thank you very much for the idea. The code has been updated.

File: apps/api-extractor/src/collector/Collector.ts [hunk 1]
```diff
@@ -292,9 +292,9 @@ export class Collector {
   private _makeUniqueNames(): void {
     const usedNames: Set<string> = new Set<string>();
 
-    // First collect the explicit package exports
+    // First collect the explicit package exports (named)
     for (const entity of this._entities) {
-      if (entity.exported) {
+      if (entity.exported && entity.originalName !== 'default') {
```
Comment (pgonzal) [inline apps/api-extractor/src/collector/Collector.ts]: > 'default' [](start = 52, length = 10)

Better to use `ts.InternalSymbolName.ExportStar` instead of handcoding this string.

File: apps/api-extractor/src/generators/DtsRollupGenerator.ts [hunk 2]
```diff
@@ -179,7 +179,11 @@ export class DtsRollupGenerator {
         }
 
         if (entity.exported) {
-          replacedModifiers = 'export ' + replacedModifiers;
+          if (entity.originalName === 'default') {
+            (span.parent || span).modification.suffix = `\nexport default ${entity.nameForEmit};`;
```
Comment (pgonzal) [inline apps/api-extractor/src/generators/DtsRollupGenerator.ts]: > (span.parent || span) [](start = 11, length = 22)

Could you separate this into a case for "span" vs "span.parent" and add a comment explaining what the parent would be if it exists?

**Comment by pgonzal** [comment]
> As far as I know, CollectorEntity `nameForEmit` is to trace the export name (and ensured that there're no name conflicts with other un-exported items), not the original declaration. So in this case, this check still works. (and I've tested it.)

@adventure-yunfei FYI the `nameForEmit` is confusing two things:  (1) for exported declarations, it represents the export name as you supposed, but (2) for non-exported declarations (e.g. a class that we forgot to export but is the return type of an exported function) it is the name in emitted the .d.ts file, and which may be renamed to avoid naming conflicts with other emitted `CollectorEntity` objects.

I believe I will need to eliminate this confusion in order solve https://github.com/Microsoft/web-build-tools/issues/950, which asks API Extractor to handle declarations such as this:

```ts
class X { }
export { X as Y }
export { X as Z }
```

(Here the `nameForEmit` should be `"X"`, but that is clearly not the export name.)

**Comment by pgonzal** [comment]
@yacinehmito I added some suggestions, but otherwise this looks good.  Thanks for adding a test project!

File: apps/api-extractor/src/collector/Collector.ts (hunk 1 above)
Comment (pgonzal) [reply apps/api-extractor/src/collector/Collector.ts]: Fixed

---
In reply to: [246239738](https://github.com/Microsoft/web-build-tools/pull/1008#discussion_r246239738) [](ancestors = 246239738)

**Comment by pgonzal** [comment]
:shipit:

**Comment by pgonzal** [comment]
This was published as AE7 beta 7.0.9

**Comment by yacinehmito** [comment]
@pgonzal Thanks for fixing them yourselves 👍

**Comment by pgonzal** [comment]
@yacinehmito FYI we have API Extractor t-shirts.  If you want one, [IM me on Gitter](https://gitter.im/pgonzal) 😄
