### PR TITLE
LockFile: process start time compatibility

### LINKED ISSUE #705: ERROR: Unexpected output from "ps" command (LockFile)
I'm running Rush in an environment where many utilities, including `ps`, have been replaced with their [BusyBox](https://busybox.net/about.html) counterparts. This means only a subset of the functionality of these utilities is available. 

In particular [the method of obtaining the start time of a process](https://github.com/Microsoft/web-build-tools/blob/master/libraries/node-core-library/src/LockFile.ts#L13) (`ps -p 1234 -o lstart`) does not work in this environment, because `ps` supports neither the `p` option nor the `lstart` column, as shown by this screenshot. 
[
screen shot 2018-06-20 at 9 41 06 am
](url)
The screenshot also shows some alternatives, such as `ps -o pid,etime`.

### PR DESCRIPTION
**Pull request by jbrekelmans**
fixes #705

Copy of https://github.com/Microsoft/web-build-tools/pull/707, but with branch renamed and a change file.

### CODE REVIEW

File: libraries/node-core-library/src/LockFile.ts [hunk 1]
```diff
@@ -6,28 +6,105 @@ import * as path from 'path';
 import * as child_process from 'child_process';
 import { setTimeout } from 'timers';
 
+/**
+ * Parses the process start time from a linux /proc/1/stat file.
+ * @param stat The contents of a linux /proc/1/stat file.
+ * @returns The process start time in yiffies.
+ */
+export function getProcessStartTimeFromProcStat (stat: string): string | undefined {
+  // Parse value 22.
```
Comment (pgonzal) [inline libraries/node-core-library/src/LockFile.ts]: Could you define 22 as a local constant in this file, and cite this text from the Linux manpage?

```
(22) starttime  %llu
The time the process started after system boot. In kernels before Linux 2.6, this value was expressed in jiffies. Since Linux 2.6, the value is expressed in clock ticks (divide by sysconf(_SC_CLK_TCK)).
The format for this field was %lu before Linux 2.6.
```

File: libraries/node-core-library/src/LockFile.ts [hunk 2]
```diff
@@ -6,28 +6,105 @@ import * as path from 'path';
...
+    // Format of stat has changed.
+    return undefined;
+  }
+  const value2: string = values.slice(1, i - 1).join(' ');
+  values = [values[0], value2].concat(values.slice(i));
+  if (values.length < 22) {
+    // Older version of linux, or non-standard configuration of linux.
+    return undefined;
+  }
+  const startTimeYiffies: string = values[21];
```
Comment (pgonzal) [inline libraries/node-core-library/src/LockFile.ts]: >startTimeYiffies [](start = 8, length = 16)

Seems that the documented units are "jiffies"

File: libraries/node-core-library/src/LockFile.ts [hunk 3]
```diff
@@ -6,28 +6,105 @@ import * as path from 'path';
...
+  // > ./'bash 2)(' -c 'OWNPID=$BASHPID;cat /proc/$OWNPID/stat'
+  // 59389 (bash 2)() S 59358 59389 59358 34818 59389 4202496 329 0 0 0 0 0 0 0 20 0 1 0
+  // > rm -rf ./'bash 2)('
+  // The output shows a stat file such that value 2 contains spaces.
+  // To still umambiguously parse such output we assume all values after the third consist of only digits...
+
+  // trimRight to remove the trailing line terminator.
+  let values: string[] = stat.trimRight().split(' ');
+  let i: number = values.length - 1;
+  while (i >= 0 && /^[0-9]+$/.test(values[i])) {
```
[the remark this answers is not in the document]
Comment (jbrekelmans) [reply libraries/node-core-library/src/LockFile.ts]: I like this, it simplifies things

File: libraries/node-core-library/src/LockFile.ts [hunk 4]
```diff
@@ -6,28 +6,105 @@ import * as path from 'path';
...
+  values = [values[0], value2].concat(values.slice(i));
+  if (values.length < 22) {
+    // Older version of linux, or non-standard configuration of linux.
+    return undefined;
+  }
+  const startTimeYiffies: string = values[21];
+  // In theory, the representations of start time returned by /proc/*/stat and ps -o lstart can change while the
+  // system is running, but we assume this does not happen.
+  // So the caller can safely use this value as part of a unique process id (on the machine, without comparing
+  // accross reboots).
```
Comment (pgonzal) [inline libraries/node-core-library/src/LockFile.ts]: There are a couple interesting points here:
- The `ps -o lstart` does print out a full date/time. If that actually did change while the system is running (e.g. due to a clock synchronization), that would be problematic for the algorithm, because it would incorrectly infer that a lock has expired.  If there was a way to improve that, it might be interesting to consider (in a separate GitHub issue)
- The `/proc/*/stat` seems to show a time relative to the kernel boot, which would get invalidated when the PC reboots. That seems pretty safe. The chances of a second process getting spawned after a reboot, with the exact same starttime and PID seems astronomically small.

File: libraries/node-core-library/src/LockFile.ts [hunk 5]
```diff
@@ -6,28 +6,105 @@ import * as path from 'path';
...
+  return startTimeYiffies;
+}
+
 /**
  * Helper function that is exported for unit tests only.
  * Returns undefined if the process doesn't exist with that pid.
  */
 export function getProcessStartTime(pid: number): string | undefined {
+  // Use toFixed() to ensure decimal representation is used when converting the PID to string, although no PID is
+  // large enough to be printed using exponential notation.
```
Comment (pgonzal) [inline libraries/node-core-library/src/LockFile.ts]: >using exponential notation [](start = 32, length = 26)

FYI `1e+31.toFixed().toString() === '1e+31'`

File: libraries/node-core-library/src/LockFile.ts [hunk 6]
```diff
@@ -6,28 +6,105 @@ import * as path from 'path';
...
 
-  const psResult: string = child_process.spawnSync('ps', args).stdout.toString();
+  const psResult: child_process.SpawnSyncReturns<string> = child_process.spawnSync('ps', args, {
+    encoding: 'utf8'
+  });
+  const psStdout: string = psResult.stdout;
+
+  // If no process with PID pid exists then the exit code is non-zero on linux.
+  // But if no process exists we do not want to fall back on /proc/*/stat to determine the process
+  // start time, so we we additionally add !psStdout.
```
Comment (pgonzal) [inline libraries/node-core-library/src/LockFile.ts]: >!psStdout [](start = 43, length = 9)

I had a little trouble understanding what `!psStdout` is testing.  My guess is that it is testing whether the `ps` command wrote more than 0 characters to its stdout stream (e.g. the header).  However at first I assumed it was testing whether the stream object was `undefined`/`null`.  Might be useful to clarify that.

**Comment by pgonzal** [comment]
Thinks for fixing this issue!  And great job on this rather difficult PR...  :-)

I've approved it.  Please reply to let us know when you're done responding to any remaining feedback, and we'll merge the PR.

File: libraries/node-core-library/src/LockFile.ts (hunk 5 above)
Comment (jbrekelmans) [reply libraries/node-core-library/src/LockFile.ts]: Wow! You're right!

**Comment by pgonzal** [comment]
@nickpape-msft  FYI

**Comment by jbrekelmans** [comment]
@pgonzal I'm finished replying to feedback!

**Comment by jbrekelmans** [comment]
Mm.. I think there's a bug thought one second..

**Comment by pgonzal** [comment]
This was published as @microsoft/rush 5.0.0-dev.25.

@jbrekelmans thanks again for doing this fix! :-)
