### PR TITLE
[rush] Fix #1392  "rush install not working on pnpm 3.5" by getting the  temporary project dependency key from the shrinkwrap

### LINKED ISSUE #1392: [rush] `Rush install` fails with Rush 5.10.1 and pnpm 3.5.3
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

Updating to Rush 5.10.1 and pnpm 3.5.3 from pnpm 2.25.7, I can now successfully `rush update` (thanks to #1347).  However, when I try to run a `rush install` it fails saying `The shrinkwrap is missing the following dependencies:`.  A subsequent `rush update` will work though.

The workflow I followed is:
1. Update rush.json
1. Delete existing `shrinkwrap.yaml`
    - `common\temp` did not exist either
1. Run `node common/scripts/install-run-rush.js update --full`.  Which succeeds and appears to work properly
    - Same issue if `rush update` instead of `--full` is run here.
1. Run `node common/scripts/install-run-rush.js install`.  This fails with the shrinkwrap is missing dependencies error.

There is a repro repo here, https://github.com/calebmshafer/imodeljs_rush_bug_repro.

**What is the expected behavior?**

I expected `rush update` to create the pnpm-lock.yaml file correctly so `rush install` works after the lock file is initially created.

**Please provide the tool version, Node.js version and OS.**

* Tool: Rush
* Tool Version: 
* Node Version: 10.15.3
* OS: Windows 10 1809

### PR DESCRIPTION
**Pull request by sachinjoseph**
Fix #1392 "rush install not working on pnpm 3.5" by getting the temporary project dependency key from the shrinkwrap.

### CODE REVIEW

File: apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts [hunk 1]
```diff
@@ -160,11 +160,29 @@ export class PnpmShrinkwrapFile extends BaseShrinkwrapFile {
...
   }
 
+  /**
+   * Gets the dependency key name of the given temporary project
+   * Examples of the return value:
+   *   file:projects/empty-webpart-project.tgz
+   *   file:projects/article-site-demo.tgz_jest@22.4.4+typescript@2.9.2
+   *   file:projects/i18n-utilities.tgz_462eaf34881863298955eb323c130fc7
+   */
+  public getTempProjectKey(tempProjectName: string): string {
```
Comment (sachinjoseph) [inline apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts]: Hmm, it doesn't make sense to expose a method called `getTempProjectKey `from the class `PnpmShrinkWrapFile`. I will rename this.

**Comment by iclanton** [comment]
Looks good to me.
