### PR TITLE
[rush] Properly handle Git worktrees

### LINKED ISSUE #990: [rush] Git hooks feature causes Rush commands to fail in worktrees
If the current directory is a [Git worktree](https://git-scm.com/docs/git-worktree) (rather than a full copy of a repo), the new Git hooks feature causes rush commands to fail:
```
Rush Multi-Project Build Tool 5.5.3 - https://rushjs.io

Starting "rush install"

Ignoring Git validation because this is not a Git working folder.

Found files in the "common/git-hooks" folder.

ERROR: EEXIST: file already exists, mkdir 'D:\git\fabric-react2\.git'
```

This is because instead of having a `.git` directory, a worktree has a `.git` *file* containing the path to the real Git metadata directory. For example:
```
gitdir: D:/git/fabric-react/.git/worktrees/fabric-react2
```

I just made a [change](https://github.com/rwjblue/git-repo-info/pull/42) to `git-repo-info` to make it return the directories containing Git metadata for the worktree and for the repo all-up. Once that's published, Rush can be updated to put hooks in the correct directory for the current worktree.

(If anyone is curious, [this blog post](https://spin.atomicobject.com/2016/06/26/parallelize-development-git-worktrees/) has a good explanation of the appeal of worktrees.)

### PR DESCRIPTION
**Pull request by ecraig12345**
When copying Git hooks in a Git working directory which is a worktree, the destination should be under the Git metadata directory for the current worktree. Copying into `path.join(repoInfo.worktreeGitDir, 'hooks')` (`repoInfo` is returned by `git-repo-info`) will give the correct results for both worktrees and normal working directories.

For example, if my main copy of a Git repo is at `D:\git\fabric-react` and the worktree I'm building in is at `D:\git\fabric-react2`, the hooks should get copied into `D:\git\fabric-react\.git\worktrees\fabric-react2\hooks` (not `D:\git\fabric-react2\.git\hooks` as it was previously attempting).

Updating `git-repo-info` to a new version which supports worktrees also makes Git email policy work in worktrees. I added typings to the latest git-repo-info version too, so the custom typings can be removed.

(Fixes #990)

### CODE REVIEW

File: apps/rush-lib/src/logic/Git.ts [hunk 1]
```diff
@@ -104,6 +112,37 @@ export class Git {
...
+  public static getGitInfo(): Readonly<gitInfo.GitRepoInfo> | undefined {
+    if (!Git._checkedGitInfo) {
+      try {
+        const repoInfo: gitInfo.GitRepoInfo = gitInfo();
+        if (Git.isPathUnderGitWorkingTree(repoInfo)) {
+          Git._gitInfo = repoInfo;
+        }
+      } catch (ex) {
+        // ignore
+      }
```
Comment (pgonzal) [inline apps/rush-lib/src/logic/Git.ts]: What kind of exceptions are we expecting to catch and ignore here?

If this throws and catches an exception as part of a normal expected state that is not an error (an "unexceptional exception"), is there a test we can add that would avoid that?  (Unexceptional exceptions make debugging harder, because when you try to use the "break on exceptions" feature it constantly stops at exceptions that don't reflect any actual problem.)

File: apps/rush-lib/src/api/ChangeFile.ts [hunk 2]
```diff
@@ -81,7 +81,7 @@ export class ChangeFile {
   public generatePath(): string {
     let branch: string | undefined = undefined;
     try {
-      branch = gitInfo().branch;
+      branch = Git.getGitInfo()!.branch;
```
Comment (pgonzal) [inline apps/rush-lib/src/api/ChangeFile.ts]: >!.branch [](start = 31, length = 8)

How do we know that `getGitInfo()` doesn't return undefined here?

Comment (ecraig12345) [reply apps/rush-lib/src/api/ChangeFile.ts]: It could, but the try/catch would catch it.

File: apps/rush-lib/src/logic/Git.ts (hunk 1 above)
Comment (ecraig12345) [reply apps/rush-lib/src/logic/Git.ts]: Added a comment and changed the try/catch to wrap only the most relevant part (which actually is very unlikely to throw)

File: apps/rush-lib/src/api/ChangeFile.ts (hunk 2 above)
Comment (pgonzal) [reply apps/rush-lib/src/api/ChangeFile.ts]: Agreed.  A null reference exception is always a program malfunction.  We would never intentionally catch this sort of exception.

---
In reply to: [241253975](https://github.com/Microsoft/web-build-tools/pull/994#discussion_r241253975) [](ancestors = 241253975)
